version: "3.7"

services:
  sponsorblock:
    image: mchangrh/sb-mirror:latest
    container_name: sponsorblock
    hostname: sponsorblock
    volumes:
      - ./mirror:/mirror
      - ./export:/export
    ports:
      - 873:873
    environment:
      - MIRROR=TRUE
      - MIRROR_URL=sponsorblock.whateveritworks.org
    restart: always
    
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    shm_size: 1g
    user: 0:0
    # ports:
    #   - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./mirror:/mirror
    environment:
      - POSTGRES_DB=sponsorblock
      - POSTGRES_PASSWORD=changethis
      - POSTGRES_USER=sponsorblock
    restart: always
    
  sponsorblock-mirror:
    image: 1337kavin/sponsorblock-mirror:latest
    container_name: sponsorblock-mirror
    hostname: sponsorblock-mirror
    volumes:
      - ./mirror:/app/mirror
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - postgres
      - sponsorblock
volumes:
  postgres_data: null
